// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfYimz6BuhsEjvnYuYadSIU9zerCiEPf4',
    appId: '1:792630821956:web:4e235fccfce374d147a811',
    messagingSenderId: '792630821956',
    projectId: 'ottsharelogin',
    authDomain: 'ottsharelogin.firebaseapp.com',
    storageBucket: 'ottsharelogin.appspot.com',
    measurementId: 'G-GC771TYPYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjnYD0jQSyAhlAVSbqBVTo5UGU55YEnI',
    appId: '1:792630821956:android:287c6cd05f27a48747a811',
    messagingSenderId: '792630821956',
    projectId: 'ottsharelogin',
    storageBucket: 'ottsharelogin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASu215uXtuhP10UPwhyCvREO5cf3Mhz_k',
    appId: '1:792630821956:ios:12d6dbeb85abcef347a811',
    messagingSenderId: '792630821956',
    projectId: 'ottsharelogin',
    storageBucket: 'ottsharelogin.appspot.com',
    androidClientId: '792630821956-174o7po8bef7uk5j7a6dkd6l39t99eq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASu215uXtuhP10UPwhyCvREO5cf3Mhz_k',
    appId: '1:792630821956:ios:12d6dbeb85abcef347a811',
    messagingSenderId: '792630821956',
    projectId: 'ottsharelogin',
    storageBucket: 'ottsharelogin.appspot.com',
    androidClientId: '792630821956-174o7po8bef7uk5j7a6dkd6l39t99eq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ottShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfYimz6BuhsEjvnYuYadSIU9zerCiEPf4',
    appId: '1:792630821956:web:92ce96e8d3f9dd2147a811',
    messagingSenderId: '792630821956',
    projectId: 'ottsharelogin',
    authDomain: 'ottsharelogin.firebaseapp.com',
    storageBucket: 'ottsharelogin.appspot.com',
    measurementId: 'G-2CSTX0103P',
  );
}
